In [5]:
#problem 1
import pandas as pd
import numpy as np
data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name": ["Amit", "Simran", "Raj", "Priya", "Neha", 
             "Arjun", "Karan", "Pooja", "Ravi", "Sneha"],
    "Age": [20, 24, 26, np.nan, 37, 43, np.nan, 50, 32, 55],
    "Salary": [50000, 60000, np.nan, 45000, 70000, 
               80000, 75000, np.nan, 67000, 52000],
    "Department": ["HR", "Finance", "IT", "Marketing", 
                   "Finance", "IT", np.nan, "HR", "IT", "Marketing"]
}

df = pd.DataFrame(data)

print(df)


   ID    Name   Age   Salary Department
0   1    Amit  20.0  50000.0         HR
1   2  Simran  24.0  60000.0    Finance
2   3     Raj  26.0      NaN         IT
3   4   Priya   NaN  45000.0  Marketing
4   5    Neha  37.0  70000.0    Finance
5   6   Arjun  43.0  80000.0         IT
6   7   Karan   NaN  75000.0        NaN
7   8   Pooja  50.0      NaN         HR
8   9    Ravi  32.0  67000.0         IT
9  10   Sneha  55.0  52000.0  Marketing


In [2]:
mean_salary = df["Salary"].mean()
print("Mean Salary:", mean_salary)


Mean Salary: 62375.0


In [3]:
median_salary = df["Salary"].median()
print("Median Salary:", median_salary)


Median Salary: 63500.0


In [4]:
main_data = df.dropna(subset=["Age", "Salary"])

weighted_mean_salary = (main_data["Age"] * main_data["Salary"]).sum() / main_data["Age"].sum()
print("Age-Weighted Mean Salary:", weighted_mean_salary)


Age-Weighted Mean Salary: 63857.81990521327


Ques- Explain when a weighted mean is preferable.
ANS-
A weighted mean is preferable when not all data points should contribute equally to the average.
means,some values are more important or carry more weight than others.
As the example given above:
Age-Weighted Salary:
If we want to reflect that salaries of older employees matter more, then we give higher weight to older ages.A simple mean would treat a 20-year-old and a 55-year-old equally, but weighted mean acknowledges the difference.
A weighted mean is preferable when different values represent different levels of importance, frequency, or contribution, so the average reflects reality more accurately.

In [8]:
#problem 2
import pandas as pd
import numpy as np
income = df["Salary"]
mean_income = income.mean()
std_income = income.std()
z_scores = (income - mean_income) / std_income
outliers = z_scores[np.abs(z_scores) > 3]
print("Mean Salary:", mean_income)
print("Standard Deviation of Salary:", std_income)
print("\nZ-scores:\n", z_scores)
print("\nNumber of Outliers:", outliers.shape[0])


Mean Salary: 62375.0
Standard Deviation of Salary: 12637.105229103245

Z-scores:
 0   -0.979259
1   -0.187939
2         NaN
3   -1.374919
4    0.603382
5    1.394702
6    0.999042
7         NaN
8    0.365986
9   -0.820995
Name: Salary, dtype: float64

Number of Outliers: 0


In [9]:
#problem 3
ages = df["Age"]
salaries = df["Salary"]
bin1 = salaries[(ages >= 18) & (ages < 25)]
bin2 = salaries[(ages >= 25) & (ages < 35)]
bin3 = salaries[(ages >= 35) & (ages < 45)]
bin4 = salaries[(ages >= 45) & (ages < 60)]
final = pd.DataFrame({
    "Age_Bin": ["18-25", "25-35", "35-45", "45-60"],
    "Count": [bin1.count(), bin2.count(), bin3.count(), bin4.count()],
    "Mean_Income": [bin1.mean(), bin2.mean(), bin3.mean(), bin4.mean()],
    "Median_Income": [bin1.median(), bin2.median(), bin3.median(), bin4.median()]
})

print(final)



  Age_Bin  Count  Mean_Income  Median_Income
0   18-25      2      55000.0        55000.0
1   25-35      1      67000.0        67000.0
2   35-45      2      75000.0        75000.0
3   45-60      1      52000.0        52000.0


In [13]:
#problem 4
import numpy as np
a = np.array([[21, 22, 23],
                [24, 25, 26],
                [27, 28, 29]])
print("array:", a)
#Shape and Resize → shape, size, Transpose, Flatten
print("\nShape of array:", a.shape)   
print("Size of array:", a.size)        
print("\nTranspose of array:\n", a.T)  
print("\nFlattened array:", a.flatten())


array: [[21 22 23]
 [24 25 26]
 [27 28 29]]

Shape of array: (3, 3)
Size of array: 9

Transpose of array:
 [[21 24 27]
 [22 25 28]
 [23 26 29]]

Flattened array: [21 22 23 24 25 26 27 28 29]


In [19]:
#Showcasing negative indexing and display error while doing slicing
print("\nLast row (negative indexing):", a[-1])  
print("Last element of last row:", a[-1, -1])    
try:
    print(a[:, 5])  
except IndexError as e:
    print("\nError during slicing:", e)


Last row (negative indexing): [27 28 29]
Last element of last row: 29

Error during slicing: index 5 is out of bounds for axis 1 with size 3


In [21]:
#Arithmetic Operations → Broadcasting, Dot Product
print("broadcasting", a + 10) 
print("\nDot product :\n", np.dot(a, a.T))


broadcasting [[31 32 33]
 [34 35 36]
 [37 38 39]]

Dot product :
 [[1454 1652 1850]
 [1652 1877 2102]
 [1850 2102 2354]]


In [23]:
#Linear Algebra → Determinant, Inverse
det = np.linalg.det(a)
print("Determinant:", det)
inverse = np.linalg.inv(a)
print("Inverse:\n", inverse)

Determinant: -2.131628207280336e-14
Inverse:
 [[ 1.40737488e+14 -2.81474977e+14  1.40737488e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 1.40737488e+14 -2.81474977e+14  1.40737488e+14]]
